optimiser: "interpolated_iLQR"
#optimiser: "stomp"
#optimiser: "gradDescent"
# pendulum = 0, acrobot = 1, reaching = 2,
# pushing cylinder = 3, pushing cylinder into mild clutter = 4, pushing cylinder heavy clutter = 5, pushing cylinder medium clutter constrained = 6
# pushing box with toppling = 7
# boxFlick = 8, boxFlickLowClutter = 9, boxFlickHeavyClutter = 10
# locomotion = 11
# hopper = 12
# boxSweep = 13
taskNumber: 2
# init control = 0, optimise once = 1, MPCContinous = 2, MPC_until_completion = 3, generateTestScenes = 4, generateTestingData = 5, generateFilteringData = 6
# generic testing = 9
displayMode: 5
# Loadmodes can be, "random", "fromCSV", "fromYAML"
taskInitMode: "fromCSV"
csvRow: 4
filtering: "none"
costDerivsFD: false
