optimiser: "interpolated_iLQR"
#optimiser: "stomp"
#optimiser: "gradDescent"
# pendulum = 0, reaching = 1, pushing cylinder = 3, pushing cylinder into mild clutter = 6
taskNumber: 6
# init control = 0, optimise once = 1, MPCContinous = 2, MPC_until_completion = 3, generateTestScenes = 4, generateTestingData = 5, generateFilteringData = 6
displayMode: 5
# Loadmodes can be, "random", "fromCSV", "fromYAML"
taskInitMode: "fromYAML"
csvRow: 15
filtering: false