modelFile: "/mujoco_models/Acrobot/acrobot.xml"
modelName: "/acrobot"
timeStep: 0.004
keypointMethod: "magvel_change"   # Possible values: "setInterval", "adaptive_jerk", "adaptive_accel", "iterative_error, "magvel_change"
minN: 1
maxN: 5
iterativeErrorThreshold: 0.001
# stable down pos [3.1415, 0], half up unstable pos [3.14, 3.14], full up unstable pos [0, 0]
robots:
  doublePendulum:
    jointNames: [shoulder, elbow]
    actuatorNames: [shoulder]
    torqueControl: true
    torqueLimits: [100]
    startPos: [3.1415, 0]
    goalPos: [0, 0]
    jointPosCosts: [0, 0]
    jointVelCosts: [0.001, 0.001]
    terminalJointPosCosts: [100, 100]
    terminalJointVelCosts: [10, 10]
    jointControlCosts: [0.0001]
    jointJerkThresholds: [0.001, 0.001]
    magVelThresholds: [0.01, 0.01]