modelFile: "/mujoco_models/walker.xml"
modelName: "/walker_locomotion"
timeStep: 0.004
robots:
  walker:
    jointNames: ["rootz", "rootx", "rooty", "right_hip", "right_knee", "right_ankle", "left_hip", "left_knee", "left_ankle"]
    actuatorNames: ["right_hip", "right_knee", "right_ankle", "left_hip", "left_knee", "left_ankle"]
    torqueControl: true
    torqueLimits: [1, 1, 1, 1, 1, 1]
    startPos: [0, 0, 0, 1, -1, 0.2, 0, 0, 0]
    goalPos: [0, 0, 0, 0.3, 0, -0.3, -0.3, 0, -0.3]
    jointPosCosts: [3, 0, 3, 0, 0, 0, 0, 0, 0]
    jointVelCosts: [0, 1, 0, 0, 0, 0, 0, 0, 0]
    jointControlCosts: [0, 0, 0, 0, 0, 0]
    jointJerkThresholds: [0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005]