modelFile: "/mujoco_models/walker.xml"
modelName: "/walker"
timeStep: 0.005
keypointMethod: "adaptive_jerk"   # Possible values: "setInterval", "adaptive_jerk", "adaptive_accel", "iterative_error, "magvel_change"
minN: 1
maxN: 5
iterativeErrorThreshold: 0.5
robots:
  walker:
    jointNames: ["rootz", "rootx", "rooty", "right_hip", "right_knee", "right_ankle", "left_hip", "left_knee", "left_ankle"]
    actuatorNames: ["right_hip", "right_knee", "right_ankle", "left_hip", "left_knee", "left_ankle"]
    torqueControl: true
    torqueLimits: [1, 1, 1, 1, 1, 1]
    startPos: [0, 0, 0, 1, -1, 0.2, 0, 0, 0]
    goalPos: [0, 0, 0, 0, 0, 0, 0, 0, 0]
    jointPosCosts: [1, 0, 1, 0, 0, 0, 0, 0, 0]
    jointVelCosts: [0, 1, 0, 0, 0, 0, 0, 0, 0]
    terminalJointPosCosts: [ 10, 0, 1, 0, 0, 0, 0, 0, 0 ]
    terminalJointVelCosts: [ 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
    jointControlCosts: [0, 0, 0, 0, 0, 0, 0]
    #jointControlCosts: [0.005, 0.001, 0.001, 0.005, 0.001, 0.001]
    jointJerkThresholds: [0.1, 0.02, 0.2, 0.4, 0.4, 0.2, 0.4, 0.4]
    #jointJerkThresholds: [0.1, 0.02, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
    magVelThresholds: [1.0, 1.0, 1.0, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]