modelFile: "/mujoco_models/walker.xml"
modelName: "/walker"
timeStep: 0.005
keypointMethod: "magvel_change"   # Possible values: "setInterval", "adaptive_jerk", "adaptive_accel", "iterative_error, "magvel_change"
minN: 1
maxN: 20
iterativeErrorThreshold: 0.1
robots:
  walker:
    jointNames: ["rootz", "rootx", "rooty", "right_hip", "right_knee", "right_ankle", "left_hip", "left_knee", "left_ankle"]
    actuatorNames: ["right_hip", "right_knee", "right_ankle", "left_hip", "left_knee", "left_ankle"]
    torqueControl: true
    torqueLimits: [1, 1, 1, 1, 1, 1]
    startPos: [0, 0, 0, 1, -1, 0.2, 0, 0, 0]
    goalPos: [0, 0, 0, 0, 0, 0, 0, 0, 0]
    jointPosCosts: [1, 0, 1, 0, 0, 0, 0, 0, 0]
    jointVelCosts: [0, 0.1, 0, 0, 0, 0, 0, 0, 0]
    terminalJointPosCosts: [ 1, 0, 1, 0, 0, 0, 0, 0, 0 ]
    terminalJointVelCosts: [ 0, 0.1, 0, 0, 0, 0, 0, 0, 0 ]
    jointControlCosts: [0.0001, 0.00001, 0.0001, 0.0001, 0.0001, 0.0001]
    #jointControlCosts: [0.005, 0.001, 0.001, 0.005, 0.001, 0.001]
#    jointJerkThresholds: [0.1, 0.02, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    jointJerkThresholds: [1e-15, 1e-15, 0.01, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]
    #jointJerkThresholds: [0.1, 0.02, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
    magVelThresholds: [0.1, 0.1, 0.001, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]