modelFile: "/mujoco_models/Acrobot/Acrobot.xml"
modelName: "/doublePendulum"
timeStep: 0.004
# stable down pos [3.1415, 0], half up unstable pos [3.14, 3.14], full up unstable pos [0, 0]
robots:
  doublePendulum:
    jointNames: [shoulder, elbow]
    numActuators: 2
    torqueControl: true 
    torqueLimits: [100, 100]
    startPos: [2, 0]
    goalPos: [3.1415, 3.1415]
    jointPosCosts: [0.2, 0.4]
    jointVelCosts: [0.1, 0.1]
    jointControlCosts: [0.003, 0.003]
    jointJerkThresholds: [0.001, 0.001]