modelFile: "/home/davidrussell/catkin_ws/src/autoTOTask/Franka-emika-panda-arm/Acrobot.xml"
robots:
  doublePendulum:
    jointNames: [shoulder, elbow]
    numActuators: 2
    jointPosCosts: [1, 1]
    jointVelCosts: [0, 0]
    jointControlCosts: [0.8, 0.8]