modelFile: "/Franka-emika-panda-arm/Acrobot.xml"
robots:
  doublePendulum:
    jointNames: [shoulder, elbow]
    numActuators: 2
    torqueControl: true 
    torqueLimits: [100, 100]
    jointPosCosts: [2, 1]
    jointVelCosts: [0, 0]
    jointControlCosts: [0.1, 0.1]