modelFile: "/home/davidrussell/catkin_ws/src/physicsSimSwitching/Franka-emika-panda-arm/V1/cheezit_pushing.xml"
robots:
  frankaArm:
    jointNames: [shoulder, elbow]
    numActuators: 7
    jointPosCosts: [1, 1, 1, 1, 1, 1, 1, 1]
    jointVelCosts: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    jointControlCosts: [0, 0, 0, 0, 0, 0, 0]
bodies:
  blueTin:
    activeLinearDOF: [true, true, false]
    activeAngularDOF: [false, false, false]
    double linearCost: [1, 1, 0]
    double angularCost: [0, 0, 0]