modelFile: "/Franka-emika-panda-arm/V1/reaching_scene.xml"
robots:
  panda:
    jointNames: ["panda0_joint1", "panda0_joint2", "panda0_joint3", "panda0_joint4", "panda0_joint5", "panda0_joint6", "panda0_joint7"]
    numActuators: 7
    torqueControl: true 
    torqueLimits: [87, 87, 87, 87, 12, 12, 12]
    startPos: [-1, 0.5, 0, -1, 0, 0.6, 1]
    goalPos: [1, 1.5, 2, -2, 0, 0.6, 1]
    jointPosCosts: [1, 1, 1, 1, 1, 1, 1, 1]
    jointVelCosts: [10, 10, 10, 10, 10, 10, 10]
    jointControlCosts: [0, 0, 0, 0, 0, 0, 0]