modelFile: "/mujoco_models/Franka_emika_scenes_V1/reaching_scene.xml"
modelName: "/panda_reaching"
timeStep: 0.004
keypointMethod: "setInterval"   # Possible values: "setInterval", "adaptive_jerk", "adaptive_accel", "iterative_error, "magvel_change"
minN: 1
maxN: 50
iterativeErrorThreshold: 0.001
robots:
  panda:
    jointNames: ["panda0_joint1", "panda0_joint2", "panda0_joint3", "panda0_joint4", "panda0_joint5", "panda0_joint6", "panda0_joint7"]
    actuatorNames: ["panda0_joint1", "panda0_joint2", "panda0_joint3", "panda0_joint4", "panda0_joint5", "panda0_joint6", "panda0_joint7"]
    torqueControl: true 
    torqueLimits: [87, 87, 87, 87, 12, 12, 12]
    startPos: [-1, 0.5, 0, -1, 0, 0.6, 1]
    goalPos: [1, 0.5, 2, -1.4, 0, 0.6, 1]
    jointPosCosts: [0, 0, 0, 0, 0, 0, 0, 0]
    jointVelCosts: [1, 1, 1, 1, 1, 1, 1, 1]
    terminalJointPosCosts: [ 100, 100, 100, 100, 100, 100, 100 ]
    terminalJointVelCosts: [ 10, 10, 10, 10, 10, 10, 10 ]
    jointControlCosts: [0, 0, 0, 0, 0, 0, 0]
    jointJerkThresholds: [0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005]
    magVelThresholds: [1.0, 1.0, 1.0, 1.0, 0.1, 0.1, 0.1]