modelFile: "/mujoco_models/Franka_emika_scenes_V1/cylinder_pushing_heavyClutter_realWorld.xml"
modelName: "/push_realWorld"
timeStep: 0.004
keypointMethod: "setInterval"   # Possible values: "setInterval", "adaptive_jerk", "adaptive_accel", "iterative_error, "magvel_change"
minN: 1
maxN: 50
iterativeErrorThreshold: 0.0001
robots:
  panda:
    jointNames: ["panda0_joint1", "panda0_joint2", "panda0_joint3", "panda0_joint4", "panda0_joint5", "panda0_joint6", "panda0_joint7"]
    actuatorNames: ["panda0_joint1", "panda0_joint2", "panda0_joint3", "panda0_joint4", "panda0_joint5", "panda0_joint6", "panda0_joint7"]
    torqueControl: true
    torqueLimits: [87, 87, 87, 87, 12, 12, 12]
    startPos: [0, -0.183, 0, -3.1, 0, 1.34, 0]
    goalPos: [0, 0, 0, 0, 0, 0, 0]
    jointPosCosts: [0, 0, 0, 0, 0, 0, 0, 0]
    jointVelCosts: [0, 0, 0, 0, 0, 0, 0]
    terminalJointPosCosts: [ 0, 0, 0, 0, 0, 0, 0 ]
    terminalJointVelCosts: [ 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05 ]
    jointControlCosts: [0, 0, 0, 0, 0, 0, 0, 0]
    jointJerkThresholds: [0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005]
    magVelThresholds: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
bodies:
  HotChocolate:
    activeLinearDOF: [true, true, false]
    activeAngularDOF: [false, false, false]
    startLinearPos: [0.4, 0.2, 0.0]
    startAngularPos: [0, 0, 0]
    goalLinearPos: [0.66, 0.07, 0.0]
    goalAngularPos: [0, 0, 0]
    linearPosCost: [ 0.05, 0.05, 0 ]
    terminalLinearPosCost: [ 100, 100, 0 ]
    linearVelCost: [ 0.05, 0.05, 0 ]
    terminalLinearVelCost: [ 0, 0, 0 ]
    angularPosCost: [ 0, 0, 0 ]
    terminalAngularPosCost: [ 0, 0, 0 ]
    angularVelCost: [ 0, 0, 0 ]
    terminalAngularVelCost: [ 0, 0, 0 ]
    linearJerkThreshold: [ 0.01, 0.01, 0.01 ]
    angularJerkThreshold: [ 0.01, 0.01, 0.01 ]
    linearMagVelThreshold: [ 0.1, 0.1, 0.1 ]
    angularMagVelThreshold: [ 0.1, 0.1, 0.1 ]
  Bistro_1:
    activeLinearDOF: [true, true, false]
    activeAngularDOF: [false, false, false]
    startLinearPos: [0.65, 0.45, 0.0]
    startAngularPos: [0, 0, 0]
    goalLinearPos: [0.65, 0.45, 0.0]
    goalAngularPos: [0, 0, 0]
    linearPosCost: [0, 0, 0]
    terminalLinearPosCost: [ 10, 10, 0 ]
    linearVelCost: [0, 0, 0]
    terminalLinearVelCost: [0, 0, 0]
    angularPosCost: [0, 0, 0]
    terminalAngularPosCost: [0, 0, 0]
    angularVelCost: [0, 0, 0]
    terminalAngularVelCost: [0, 0, 0]
    linearJerkThreshold: [ 0.02, 0.02, 0.02  ]
    angularJerkThreshold: [ 0.02, 0.02, 0.02  ]
    linearMagVelThreshold: [ 0.1, 0.1, 0.1 ]
    angularMagVelThreshold: [ 0.1, 0.1, 0.1 ]
  Bistro_2:
    activeLinearDOF: [ true, true, false ]
    activeAngularDOF: [ false, false, false ]
    startLinearPos: [ 0.68, 0.3, 0.0 ]
    startAngularPos: [ 0, 0, 0 ]
    goalLinearPos: [ 0.68, 0.3, 0.0 ]
    goalAngularPos: [ 0, 0, 0 ]
    linearPosCost: [0, 0, 0]
    terminalLinearPosCost: [ 10, 10, 0 ]
    linearVelCost: [0, 0, 0]
    terminalLinearVelCost: [0, 0, 0]
    angularPosCost: [0, 0, 0]
    terminalAngularPosCost: [0, 0, 0]
    angularVelCost: [0, 0, 0]
    terminalAngularVelCost: [0, 0, 0]
    linearJerkThreshold: [ 0.02, 0.02, 0.02  ]
    angularJerkThreshold: [ 0.02, 0.02, 0.02  ]
    linearMagVelThreshold: [ 0.1, 0.1, 0.1 ]
    angularMagVelThreshold: [ 0.1, 0.1, 0.1 ]
  Bistro_3:
    activeLinearDOF: [ true, true, false ]
    activeAngularDOF: [ false, false, false ]
    startLinearPos: [ 0.68, 0.3, 0.2 ]
    startAngularPos: [ 0, 0, 0 ]
    goalLinearPos: [ 0.68, 0.3, 0.2 ]
    goalAngularPos: [ 0, 0, 0 ]
    linearPosCost: [0, 0, 0]
    terminalLinearPosCost: [ 10, 10, 0 ]
    linearVelCost: [0, 0, 0]
    terminalLinearVelCost: [0, 0, 0]
    angularPosCost: [0, 0, 0]
    terminalAngularPosCost: [0, 0, 0]
    angularVelCost: [0, 0, 0]
    terminalAngularVelCost: [0, 0, 0]
    linearJerkThreshold: [ 0.02, 0.02, 0.02  ]
    angularJerkThreshold: [ 0.02, 0.02, 0.02  ]
    linearMagVelThreshold: [ 0.1, 0.1, 0.1 ]
    angularMagVelThreshold: [ 0.1, 0.1, 0.1 ]
  Bistro_4:
    activeLinearDOF: [ true, true, false ]
    activeAngularDOF: [ false, false, false ]
    startLinearPos: [ 0.5, 0.2, 0.0 ]
    startAngularPos: [ 0, 0, 0 ]
    goalLinearPos: [ 0.5, 0.2, 0.0 ]
    goalAngularPos: [ 0, 0, 0 ]
    linearPosCost: [0, 0, 0]
    terminalLinearPosCost: [ 10, 10, 0 ]
    linearVelCost: [0, 0, 0]
    terminalLinearVelCost: [0, 0, 0]
    angularPosCost: [0, 0, 0]
    terminalAngularPosCost: [0, 0, 0]
    angularVelCost: [0, 0, 0]
    terminalAngularVelCost: [0, 0, 0]
    linearJerkThreshold: [ 0.02, 0.02, 0.02  ]
    angularJerkThreshold: [ 0.02, 0.02, 0.02  ]
    linearMagVelThreshold: [ 0.1, 0.1, 0.1 ]
    angularMagVelThreshold: [ 0.1, 0.1, 0.1 ]
  Bistro_5:
    activeLinearDOF: [ true, true, false ]
    activeAngularDOF: [ false, false, false ]
    startLinearPos: [ 0.55, 0.45, 0.0 ]
    startAngularPos: [ 0, 0, 0 ]
    goalLinearPos: [ 0.55, 0.45, 0.0 ]
    goalAngularPos: [ 0, 0, 0 ]
    linearPosCost: [0, 0, 0]
    terminalLinearPosCost: [ 100, 100, 0 ]
    linearVelCost: [0, 0, 0]
    terminalLinearVelCost: [0, 0, 0]
    angularPosCost: [0, 0, 0]
    terminalAngularPosCost: [0, 0, 0]
    angularVelCost: [0, 0, 0]
    terminalAngularVelCost: [0, 0, 0]
    linearJerkThreshold: [ 0.02, 0.02, 0.02  ]
    angularJerkThreshold: [ 0.02, 0.02, 0.02  ]
    linearMagVelThreshold: [ 0.1, 0.1, 0.1 ]
    angularMagVelThreshold: [ 0.1, 0.1, 0.1 ]
  Bistro_6:
    activeLinearDOF: [ true, true, false ]
    activeAngularDOF: [ false, false, false ]
    startLinearPos: [ 0.6, 0.15, 0.0 ]
    startAngularPos: [ 0, 0, 0 ]
    goalLinearPos: [ 0.6, 0.15, 0.0 ]
    goalAngularPos: [ 0, 0, 0 ]
    linearPosCost: [0, 0, 0]
    terminalLinearPosCost: [ 10, 10, 0 ]
    linearVelCost: [0, 0, 0]
    terminalLinearVelCost: [0, 0, 0]
    angularPosCost: [0, 0, 0]
    terminalAngularPosCost: [0, 0, 0]
    angularVelCost: [0, 0, 0]
    terminalAngularVelCost: [0, 0, 0]
    linearJerkThreshold: [ 0.02, 0.02, 0.02  ]
    angularJerkThreshold: [ 0.02, 0.02, 0.02  ]
    linearMagVelThreshold: [ 0.1, 0.1, 0.1 ]
    angularMagVelThreshold: [ 0.1, 0.1, 0.1 ]
  Bistro_7:
    activeLinearDOF: [ true, true, false ]
    activeAngularDOF: [ false, false, false ]
    startLinearPos: [ 0.75, 0.5, 0.0 ]
    startAngularPos: [ 0, 0, 0 ]
    goalLinearPos: [ 0.5, 0.5, 0.0 ]
    goalAngularPos: [ 0, 0, 0 ]
    linearPosCost: [0, 0, 0]
    terminalLinearPosCost: [ 10, 10, 0 ]
    linearVelCost: [0, 0, 0]
    terminalLinearVelCost: [0, 0, 0]
    angularPosCost: [0, 0, 0]
    terminalAngularPosCost: [0, 0, 0]
    angularVelCost: [0, 0, 0]
    terminalAngularVelCost: [0, 0, 0]
    linearJerkThreshold: [ 0.02, 0.02, 0.02 ]
    angularJerkThreshold: [ 0.02, 0.02, 0.02 ]
    linearMagVelThreshold: [ 0.1, 0.1, 0.1 ]
    angularMagVelThreshold: [ 0.1, 0.1, 0.1 ]
