#--------------------------------------------------------------------------------------------------
#                                     General config file
# -------------------------------------------------------------------------------------------------

task: "box_sweep"  # Task to be performed
# Current implemented tasks are:
# "double_pendulum", "acrobot", "reaching", "pushing_no_clutter", "pushing_low_clutter",
# "pushing_moderate_clutter", "pushing_moderate_clutter_constrained",
# "box_push_toppling", "box_flick_no_clutter", "box_flick_low_clutter", "box_flick_moderate_clutter",
# "walker_walk", "walker_run", "walker_uneven", ""hopper", "box_sweep", "3D_pushing", "pentabot"

optimiser: "interpolated_iLQR"  # Possible optimisers: "interpolated_iLQR", "stomp", "gradDescent"

runMode: "Optimise_once"
# Valid runModes are:
# "Init_controls"           - Displays the initial controls on repeat.
# "Optimise_once"           - Optimise the trajectory open loop, display the optimised controls and initial controls repeatedly.
# "MPC_until_completion"    - Perform MPC until the task is completed. Display current state of the system.

# Extra testing modes for debugging/generating testing data
# "Generate_test_scenes"    - Generate a set of randomly generated test scenes for the task.
# "Generate_testing_data"   - Loop through all test scenes and evaluate the Optimiser and key-point performance.
# "Generate_filtering_data" - Loop through all test scenes and evaluate baseline optimisation with and without filtering.

taskInitMode: "fromYAML"   # taskInitMode can be, "random", "fromCSV", "fromYAML"
csvRow: 5                 # CSV row to load if taskInitMode is "fromCSV" (0 - 99)

filtering: "none"         # FIR or low_pass or none - Filtering of derivative values over trajectory length.
costDerivsFD: false       # True or false, for FD computation of cost derivatives (makes things slower, use analytical if available)

minIter: 3                # Minimum number of iterations to run Optimiser for
maxIter: 10               # Maximum number of iterations to run Optimiser for
maxHorizon: 4000          # Maximum number of times-steps for optimisation horizon
