#--------------------------------------------------------------------------------------------------
#                                     General config file
# -------------------------------------------------------------------------------------------------

task: "walker"  # Task to be performed
# Current implemented tasks are:
# "double_pendulum", "acrobot", "reaching", "pushing_no_clutter", "pushing_low_clutter",
# "pushing_moderate_clutter", "pushing_moderate_clutter_constrained",
# "box_push_toppling", "box_flick_no_clutter", "box_flick_low_clutter", "box_flick_moderate_clutter",
# "walker", "walker_uneven", "hopper", "box_sweep"box_sweep

optimiser: "interpolated_iLQR"  # Possible optimisers: "interpolated_iLQR", "stomp", "gradDescent"

# init control = 0, optimise once = 1, MPCContinous = 2, MPC_until_completion = 3, generateTestScenes = 4, generateTestingData = 5, generateFilteringData = 6
# generic testing = 9
runMode: "MPC_until_completion"
# Valid runModes are:
# "Init_controls"           - Displays the initial controls on repeat.
# "Optimise_once"           - Optimise the trajectory open loop, display the optimised controls and initial controls repeatedly.
# "MPC_continuous"          - Perform MPC continuously until program terminated. Display current state of the system.
# "MPC_until_completion"    - Perform MPC until the task is completed. Display current state of the system.
# Extra testing modes for debugging/generating testing data
# "Generate_test_scenes"    - Generate a set of randomly generated test scenes for the task.
# "Generate_testing_data"   - Loop through all test scenes and evaluate the Optimiser and key-point performance.
# "Generate_filtering_data" - Loop through all test scenes and evaluate baseline optimisation with and without filtering.

taskInitMode: "fromCSV"   # taskInitMode can be, "random", "fromCSV", "fromYAML"
csvRow: 0                 # CSV row to load if taskInitMode is "fromCSV" (0 - 99)

filtering: "none"         # FIR or low_pass or none - Filterting of derivative values over trajectory length.
costDerivsFD: false       # True or false, for FD computation of cost derivatives (makes things slower, use analytical if available)

minIter: 3                # Minimum number of iterations to run Optimiser for
maxIter: 10               # Maximum number of iterations to run Optimiser for
maxHorizon: 4000          # Maximum number of times-steps for optimisation horizon
